"""
Core data structures for the OID framework.

Implements the formal model:
    - PatternState ∈ {H, C+, E, B}
    - ActionPattern = (state, value, audit_flag)
    - OperationalEpisode = non-trivial adaptation event
    - AgentProfile = accumulated operational state
    - TaskDescriptor = task with reversibility and impact
"""

from __future__ import annotations

import math
from dataclasses import dataclass, field
from enum import Enum
from typing import Optional


class PatternState(Enum):
    """
    State machine for action patterns.

    H   — active hypothesis, untested heuristic
    CP  — confirmed positive, validated in diverse conditions
    E   — eliminated, invalidated by evidence
    B   — biased pseudo-knowledge, falsely generalised
    """
    H = "H"
    CP = "C+"
    E = "E"
    B = "B"


@dataclass
class ActionPattern:
    """
    Learned action heuristic generated by an operational episode.

    Corresponds to u_{N_i} in V4.2:
        u_{N_i}(T) = (s_i(T), v_i(T), a_i(T))

    Attributes:
        pattern_id:   unique identifier
        state:        current state in {H, C+, E, B}
        value:        confidence / strength ∈ [-1, 1]
        audit_flag:   marked for review (0 or 1)
        created_at:   timestep of creation
        last_used:    timestep of last reuse
        usage_count:  number of times reused
        bias_onset:   timestep when state transitioned to B (if ever)
        domains:      set of domains co-mobilised (cross-domain trace)
        task_id:      task this pattern applies to
    """
    pattern_id: str
    state: PatternState = PatternState.H
    value: float = 0.5
    audit_flag: int = 0
    created_at: int = 0
    last_used: int = 0
    usage_count: int = 1
    bias_onset: Optional[int] = None
    domains: set = field(default_factory=set)
    task_id: Optional[str] = None

    def decay(self, T: int, delta: float = 0.05) -> None:
        """Natural decay for state H: clean disappearance, not corruption."""
        if self.state == PatternState.H:
            self.value *= math.exp(-delta * (T - self.last_used))

    def damage(self, T: int, tau_ref: float = 10.0) -> float:
        """
        Compute damage for state B.
        damage_i(T) = |v_i| * usage_i(T) * log(1 + (T - t_{B,i}) / τ_ref)
        """
        if self.state != PatternState.B or self.bias_onset is None:
            return 0.0
        return (
            abs(self.value)
            * self.usage_count
            * math.log(1 + (T - self.bias_onset) / tau_ref)
        )

    def weight(self, T: int) -> float:
        """
        Contribution weight for cross-domain entropy.
        w_i = 1 if C+, v_i(T) if H, 0 if E or B.
        """
        if self.state == PatternState.CP:
            return 1.0
        elif self.state == PatternState.H:
            return max(0.0, self.value)
        return 0.0


@dataclass
class TaskDescriptor:
    """
    A task with its frontier characteristics.

    Attributes:
        task_id:         unique identifier
        mu:              reversibility × observability ∈ [0, 1]
                         (low = irreversible/opaque; high = safe/observable)
        psi:             systemic impact radius ≥ 0
        n_min:           minimum grounding stock for safe execution
        exposure_weight: relative frequency / importance π_τ
    """
    task_id: str
    mu: float = 0.5
    psi: float = 1.0
    n_min: float = 3.0
    exposure_weight: float = 1.0

    def __post_init__(self):
        assert 0 <= self.mu <= 1, f"mu must be in [0,1], got {self.mu}"
        assert self.psi >= 0, f"psi must be >= 0, got {self.psi}"


@dataclass
class OperationalEpisode:
    """
    A non-trivial adaptation event where the agent handled uncertainty.

    Corresponds to N_i in V4.2, qualified by:
        - id_inconnu: identified the real structure of the problem
        - pert_sys:   systemic viability of the response
        - vision:     prospective discernment

    In agent terms: an episode where the agent had to adapt
    beyond procedural execution (error recovery, novel situation,
    strategy revision).
    """
    episode_id: str
    timestep: int
    task_id: str
    pattern: ActionPattern
    parent_episodes: list = field(default_factory=list)
    edge_types: dict = field(default_factory=dict)  # parent_id -> "constitutive"|"supportive"
    domains_mobilised: set = field(default_factory=set)


@dataclass
class AgentProfile:
    """
    Accumulated operational state of an autonomous AI agent.

    This is the agent-level analogue of the individual I in V4.2.
    """
    agent_id: str
    episodes: list = field(default_factory=list)
    patterns: dict = field(default_factory=dict)  # pattern_id -> ActionPattern
    capability: float = 0.8  # S_{IA_brut}: raw capability ∈ [0, 1]
    mastery: float = 0.7     # M_{IA}: operational mastery ∈ [0, 1)
    domain_stocks: dict = field(default_factory=dict)  # domain -> N_eff

    @property
    def n_episodes(self) -> int:
        return len(self.episodes)

    def stock(self, T: int) -> float:
        """N^D_stock(T) = Σ_{C+} 1 + Σ_{H} v_i(T)"""
        return sum(
            p.weight(T) for p in self.patterns.values()
        )

    def bias_load(self, T: int) -> float:
        """B^D_load(T) = Σ_{B} damage_i(T)"""
        return sum(
            p.damage(T) for p in self.patterns.values()
        )

    def n_eff(self, T: int) -> float:
        """N^D_eff(T) = stock - bias_load"""
        return self.stock(T) - self.bias_load(T)

    def debt(self, T: int) -> float:
        """Debt^D(T) = max(0, -N_eff(T))"""
        return max(0.0, -self.n_eff(T))

    def s_ia_eff(self, T: int, c_flow: float = 0.5, v_sia: float = 0.1) -> float:
        """
        Effective AI capability for this agent.
        S_{IA_eff} = S_{IA_brut} * M_{IA} * exp(-v / (1 + C_flow))
        """
        return (
            self.capability
            * self.mastery
            * math.exp(-v_sia / (1 + c_flow))
        )
