"""Render an :class:`AuditReport` as a PR-comment-ready Markdown summary."""

from __future__ import annotations

from pathlib import Path

from oida_code.models.audit_report import AuditReport, VerdictLabel

_VERDICT_BADGE: dict[VerdictLabel, str] = {
    "verified": "🟢 **verified**",
    "counterexample_found": "🔴 **counterexample_found**",
    "insufficient_evidence": "🟡 **insufficient_evidence**",
    "corrupt_success": "⚠️ **corrupt_success**",
}


def _format_optional_float(value: float | None, digits: int = 3) -> str:
    if value is None:
        return "_not computed in Phase 1_"
    return f"`{round(value, digits)}`"


def render_markdown(report: AuditReport) -> str:
    """Return a Markdown block summarizing the report."""
    summary = report.summary
    badge = _VERDICT_BADGE.get(summary.verdict, summary.verdict)

    lines: list[str] = [
        "# OIDA Code Audit",
        "",
        f"**Verdict:** {badge}",
        "",
        "## Summary",
        "",
        f"- mean `Q_obs`: {_format_optional_float(summary.mean_q_obs)}",
        f"- mean `grounding`: {_format_optional_float(summary.mean_grounding)}",
        f"- total `V_net`: {_format_optional_float(summary.total_v_net)}",
        f"- final `debt`: {_format_optional_float(summary.debt_final)}",
        f"- `corrupt_success_ratio`: {_format_optional_float(summary.corrupt_success_ratio)}",
        "",
    ]

    if report.tool_evidence:
        lines.append("## Tool evidence")
        lines.append("")
        lines.append("| Tool | Status | Duration (ms) | Findings | Counts |")
        lines.append("|---|---|---:|---:|---|")
        for ev in report.tool_evidence:
            counts = ", ".join(f"{k}={v}" for k, v in sorted(ev.counts.items())) or "—"
            lines.append(
                f"| `{ev.tool}` | `{ev.status}` | {ev.duration_ms} | "
                f"{len(ev.findings)} | {counts} |"
            )
        lines.append("")

    if report.critical_findings:
        lines.append("## Critical findings")
        lines.append("")
        for f in report.critical_findings:
            loc = f"`{f.path}`" + (f":{f.line}" if f.line else "")
            lines.append(f"- **{f.id}** · {loc} · `{f.kind}` — {f.title}")
        lines.append("")

    if report.repair.reopen or report.repair.audit or report.repair.next_prompts:
        lines.append("## Repair plan")
        lines.append("")
        if report.repair.reopen:
            lines.append(f"- **reopen:** {', '.join(f'`{e}`' for e in report.repair.reopen)}")
        if report.repair.audit:
            lines.append(f"- **audit:** {', '.join(f'`{e}`' for e in report.repair.audit)}")
        if report.repair.next_prompts:
            lines.append("- **next prompts:**")
            for p in report.repair.next_prompts:
                lines.append(f"  - {p}")
        lines.append("")

    lines.append("---")
    lines.append("_Generated by [`oida-code`](https://github.com/yannabadie/oida-code)._")
    return "\n".join(lines).rstrip() + "\n"


def write_markdown_report(report: AuditReport, path: Path | str) -> Path:
    target = Path(path)
    target.parent.mkdir(parents=True, exist_ok=True)
    target.write_text(render_markdown(report), encoding="utf-8")
    return target


__all__ = ["render_markdown", "write_markdown_report"]
