"""Render an :class:`AuditReport` as diagnostic-only Markdown."""

from __future__ import annotations

from pathlib import Path

from oida_code.models.audit_report import AuditReport, VerdictLabel

_DIAGNOSTIC_STATUS: dict[VerdictLabel, str] = {
    "verified": (
        "No contradiction observed by configured deterministic checks "
        "(diagnostic only; not proof of correctness)"
    ),
    "counterexample_found": (
        "Contradicted by deterministic evidence (human review required)"
    ),
    "insufficient_evidence": "Evidence gap remains (human review required)",
    "corrupt_success": (
        "Success evidence conflicts with critical findings "
        "(human review required)"
    ),
}


def _format_optional_float(value: float | None, digits: int = 3) -> str:
    if value is None:
        return "_not computed in Phase 1_"
    return f"`{round(value, digits)}`"


def render_markdown(report: AuditReport) -> str:
    """Return a diagnostic-only Markdown block summarizing the report."""
    summary = report.summary
    diagnostic_status = _DIAGNOSTIC_STATUS.get(
        summary.verdict,
        "Diagnostic status unavailable (human review required)",
    )

    lines: list[str] = [
        "# OIDA Code Diagnostic Report",
        "",
        "> Diagnostic only - not a merge decision or production-readiness assessment.",
        "",
        "## Diagnostic status",
        "",
        f"- Result: **{diagnostic_status}**",
        "- Mode: `diagnostic_only`",
        (
            "- Compatibility note: JSON and SARIF keep the legacy internal "
            "schema values; this Markdown is the human-facing diagnostic view."
        ),
        "",
        "## Summary",
        "",
        f"- mean `Q_obs`: {_format_optional_float(summary.mean_q_obs)}",
        f"- mean `grounding`: {_format_optional_float(summary.mean_grounding)}",
        "- Official net-value field: **blocked** (not emitted by this renderer)",
        "- Official final-debt field: **blocked** (not emitted by this renderer)",
        (
            "- Official corrupt-success ratio field: **blocked** "
            "(not emitted by this renderer)"
        ),
        "",
    ]

    if report.tool_evidence:
        lines.append("## Tool evidence")
        lines.append("")
        lines.append("| Tool | Status | Duration (ms) | Findings | Counts |")
        lines.append("|---|---|---:|---:|---|")
        for ev in report.tool_evidence:
            counts = ", ".join(f"{k}={v}" for k, v in sorted(ev.counts.items())) or "-"
            lines.append(
                f"| `{ev.tool}` | `{ev.status}` | {ev.duration_ms} | "
                f"{len(ev.findings)} | {counts} |"
            )
        lines.append("")

    if report.critical_findings:
        lines.append("## Critical findings")
        lines.append("")
        for f in report.critical_findings:
            loc = f"`{f.path}`" + (f":{f.line}" if f.line else "")
            lines.append(f"- **{f.id}** | {loc} | `{f.kind}` - {f.title}")
        lines.append("")

    if report.repair.reopen or report.repair.audit or report.repair.next_prompts:
        lines.append("## Human follow-up checklist")
        lines.append("")
        if report.repair.reopen:
            lines.append(
                f"- **review again:** {', '.join(f'`{e}`' for e in report.repair.reopen)}"
            )
        if report.repair.audit:
            lines.append(
                f"- **inspect evidence:** {', '.join(f'`{e}`' for e in report.repair.audit)}"
            )
        if report.repair.next_prompts:
            lines.append("- **reviewer prompts:**")
            for p in report.repair.next_prompts:
                lines.append(f"  - {p}")
        lines.append("")

    lines.append("---")
    lines.append("_Generated by [`oida-code`](https://github.com/yannabadie/oida-code)._")
    return "\n".join(lines).rstrip() + "\n"


def write_markdown_report(report: AuditReport, path: Path | str) -> Path:
    target = Path(path)
    target.parent.mkdir(parents=True, exist_ok=True)
    target.write_text(render_markdown(report), encoding="utf-8")
    return target


__all__ = ["render_markdown", "write_markdown_report"]
